dependencies:
  - python=3.8
  - scikit-learn
  - numpy
  - pandas
  - pip:
    - azureml-defaults
    - inference-schema
    - azureml-automl-core
    - azureml-interpret
    - azureml-automl-runtime
    - joblib
    - xgboost==1.4.2
  
